apiVersion: v1
data:
  script.js: |
    db = db.getSiblingDB("{{ .Values.dBCredentials.database }}")
    db.createUser(
      {
        user: "{{ .Values.dBCredentials.user }}",
        pwd: "{{ .Values.dBCredentials.password }}",
        roles: [
          { role: "dbOwner", db: "{{ .Values.dBCredentials.database }}" }
        ]
      }
    )
kind: ConfigMap
metadata:
  name: mongodb-scripts
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
